;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/db_config.clj
(ns config.db
  (:use [korma.db]
        [korma.core]))

(def db (postgres {:db "{{ web_db_name }}"
                   :user "{{ web_db_user }}"
                   :password "{{ web_db_pass }}"
                   :host "{{ web_db_host }}"
                   :port "{{ web_db_port }}"
                   :delimiters ""}))

(defdb app-db db)
