;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/neo4j.clj
(ns config.neo4j)

(def neonode-host {{ neo_node_host | to_json }})
(def neonode-port {{ neo_node_port | to_json }})
