var _ = require('lodash');
var fs = require('fs');
var gulp = require('gulp');
var browserify = require('browserify');
var watchify = require('watchify');
var shimify = require('browserify-shim');
var plumber = require('gulp-plumber');
var uglify = require('gulp-uglify');
var notifier = require('node-notifier');
var util = require('gulp-util');
var gulpif = require('gulp-if');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');
var path = require('path');
var prefixer = require('gulp-autoprefixer');
var minify = require('gulp-minify-css');
// var deasync = require('deasync');
var rev = require('git-rev');
var reactify = require('reactify');
var through2 = require('through2');

require('./gulp/bower.js');
require('./gulp/browserify.js');

////////////////////////////////////////////////////////////////////////////////
// sass
function sassDev() {
  return gulp.src('./sass/main.scss')
    .pipe(plumber({errorHandler: error}))
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(prefixer())
    .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest('./resources/public/css'));
}

function sassProd() {
  return gulp.src('./sass/main.scss')
    .pipe(plumber({errorHandler: error}))
    .pipe(sass())
    .pipe(prefixer())
    .pipe(minify())
    .pipe(gulp.dest('./resources/public/css'));
}

gulp.task('sass-dev', ['bower'], function(){
  return sassDev();
});

gulp.task('sass-prod', ['bower'], function(){
  return sassProd();
});

gulp.task('sass-dev-watch', function(){
  return sassDev();
});

gulp.task('sass-watch', function(){
  gulp.watch('./sass/**/*.scss', ['sass-dev-watch']);
});

gulp.task('symlink', ['bower'], function(){
  var source = path.normalize(process.cwd() + '/./resources/public/bower');
  var dest = path.normalize('./sass/bower');

  // check if the destination is already exist
  var stat;
  try{
    stat = fs.lstatSync(dest);
    // exist, remove it
    fs.unlinkSync(dest);
  } catch(e){
    // Not exist, just don't care
  }
  fs.symlinkSync(source, dest);
});

//////////////////////////////////////////////////////////////////////
// update version
gulp.task('update-version', function(){
  var revExec = deasync(rev.long);
  var hash;
  try {
    hash = revExec();
  } catch(err) {
    hash = err;                   // still don't know why hash come into error :LOL:
  }

  var fileContent = "";
  fileContent +=  ";;; GENERATED BY GULP, DO NOT EDIT\n";
  fileContent += "(ns app.views.version)\n";
  fileContent += "(def version \"" + hash + "\")\n";

  var configFile = 'src/app/views/version.clj';
  fs.writeFileSync(configFile, fileContent);
});

// combine
gulp.task('dev', ['bower', 'js-dev','symlink']);
gulp.task('prod', ['bower', 'js-prod', 'symlink']);
gulp.task('watch', ['js-watch']);
