;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/neo4j.clj
(ns config.neo4j
  (:require [clojurewerkz.neocons.rest :as nr]))

;; connects to a Neo4J Server with default username neo4j and password
(def conn (nr/connect "http://neo4j:9693f515a9e71b3b088e3a7ccaa7cf4d@localhost:7474/db/data"))
