;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/system_config.clj

;;; The config here will be merged with the config in src/config/main.clj to
;;; product the final main config
(ns config.system)

(def config
  {:ring-port 3000
   :nrepl-port 7888
   :person-image-path "/vagrant/resources/public/person-image"
   :person-image-path-original "/vagrant/resources/public/person-image/original"
   :person-image-path-square "/vagrant/resources/public/person-image/square"
   :person-image-path-small "/vagrant/resources/public/person-image/small"})
