;;; GENERATED BY ANSIBLE. DO NOT EDIT
;;; EDIT TEMPLATE IN ansible/templates/system_config.clj

;;; The config here will be merged with the config in src/config/main.clj to
;;; product the final main config
(ns config.system)

(def config
  {:ring-port {{ring_port}}
   :nrepl-port {{nrepl_port}}
   :person-image-path "{{person_image_dir}}"
   :person-image-path-original "{{person_image_dir}}/original"
   :person-image-path-square "{{person_image_dir}}/square"
   :person-image-path-small "{{person_image_dir}}/small"})
