#
POST http://pd.dev:4004/add
Content-Type: application/json

{
  "husbandNodeId": 2,
  "wifeNodeId": 5
}

#
GET http://pd.dev:4004/find/partners
Content-Type: application/json

{
  "personNodeId": 2
}

#
GET http://pd.dev:4004/detect/partnerRole/single
Content-Type: application/json

{
  "gender": "female"
}

