#
POST http://pd.dev:4000/add
Content-Type: application/json

{
  "fullName": "f2",
  "gender": "female",
  "birthDate": "05/04/1992",
  "aliveStatus": "dead"
}

#
POST http://pd.dev:4000/delete
Content-Type: application/json

{
  "personId": 3
}

#
GET http://pd.dev:4000/find/root
Content-Type: application/json

{
}

#
GET http://pd.dev:4000/find/byId
Content-Type: application/json

{
  "personId": 5
}

#
GET http://pd.dev:4000/find/byIds
Content-Type: application/json

{
  "personIds": [2, 3, 4]
}

#
GET http://pd.dev:4000/count
Content-Type: application/json

{
}

#
GET http://pd.dev:4000/find/byName
Content-Type: application/json

{
  "name": "root"
}

#
GET http://pd.dev:4000/find/byGenders
Content-Type: application/json

{
  "genders": ["unknown"]
}

#
POST http://pd.dev:4000/update
Content-Type: application/json

{
  "id": 7,
  "fullName": "f2",
  "gender": "female"
}
