#
POST http://pd.dev:4000/add
Content-Type: application/json

{
  "fullName": "mother",
  "gender": "male",
  "birthDate": "05/04/1992",
  "aliveStatus": "dead"
}

#
POST http://pd.dev:4000/delete
Content-Type: application/json

{
  "personId": 46,
  "fullName": "truong xuan 6",
  "gender": "male"
}

#
GET http://pd.dev:4000/find/root
Content-Type: application/json

{
}

#
GET http://pd.dev:4000/count
Content-Type: application/json

{
}
