#
POST http://pd.dev:4002/user/add
Content-Type: application/json

{
  "user": {
    "fullName": "Tran Xuan Truong",
    "username": "tmtxt",
    "password": "123456"
  },
  "userRole": {
    "roleName": "admin"
  }
}
